# Utiliza una imagen base de Python
FROM python:3.9

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de requerimientos (requirements.txt) al contenedor
COPY requirements.txt .

# Instala las dependencias del proyecto
RUN pip install -r requirements.txt

# Copia todo el contenido de tu proyecto al contenedor
COPY . .

# Define el comando para ejecutar tu proyecto Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]


