# Generated by Django 4.2 on 2023-06-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cambios',
            fields=[
                ('id_cambio', models.AutoField(primary_key=True, serialize=False)),
                ('minuto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cambios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id_fecha', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fixture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goles',
            fields=[
                ('id_gol', models.AutoField(primary_key=True, serialize=False)),
                ('minuto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id_jugador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jugador', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jugadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'partidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('minuto', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'tarjetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipotarjeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'tipotarjeta',
                'managed': False,
            },
        ),
    ]
