# Generated by Django 4.2 on 2023-06-28 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixture.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='PublicidadLateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicidades_laterales')),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fixture.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='PublicidadHorizontal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicidades_horizontales')),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fixture.negocio')),
            ],
        ),
    ]
