# Generated by Django 4.2 on 2023-06-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0002_localidad_negocio_publicidadlateral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='id_estado',
            field=models.ForeignKey(blank=True, db_column='id_estado', limit_choices_to={'nombre__in': ['Activo', 'Inactivo']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fixture.estados'),
        ),
    ]
